from __future__ import annotations

from typing import Any


AGENT_IDENTITIES: list[dict[str, Any]] = [
    {
        "agent_name": "Manager Agent",
        "identity": "OfficeOps task coordinator",
        "responsibility": "orchestration, state transitions, retry, final result",
        "inputs": ["StructuredIncident"],
        "outputs": ["TaskResult", "TaskState"],
        "skills": [],
        "tools": [],
        "permissions": ["dispatch_workers", "read_shared_state", "write_trace"],
        "context_memory": "current TaskState and complete trace",
        "risk_boundary": "cannot directly mutate enterprise systems",
        "upstream": ["human/operator"],
        "downstream": ["Context Agent", "Diagnosis Agent", "Remediation & Verification Agent"],
        "failure_strategy": "retry verified medium-risk action once, otherwise fail closed",
    },
    {
        "agent_name": "Context Agent",
        "identity": "enterprise evidence collector",
        "responsibility": "collect identity, VPN, permission, service, and access context",
        "inputs": ["StructuredIncident"],
        "outputs": ["EmployeeContext"],
        "skills": ["EmployeeContextSkill"],
        "tools": ["IAMTool", "VPNTool", "ApplicationTool", "ServiceHealthTool"],
        "permissions": ["read_status"],
        "context_memory": "incident input only",
        "risk_boundary": "read-only",
        "upstream": ["Manager Agent"],
        "downstream": ["Diagnosis Agent"],
        "failure_strategy": "stop and report missing evidence",
    },
    {
        "agent_name": "Diagnosis Agent",
        "identity": "access root-cause analyst",
        "responsibility": "derive root cause and safe recommended action from evidence",
        "inputs": ["EmployeeContext"],
        "outputs": ["DiagnosisResult"],
        "skills": ["AccessDiagnosisSkill"],
        "tools": [],
        "permissions": ["read_shared_state"],
        "context_memory": "structured context only",
        "risk_boundary": "cannot execute remediation",
        "upstream": ["Context Agent"],
        "downstream": ["Manager Agent"],
        "failure_strategy": "return unknown_root_cause; never guess an action",
    },
    {
        "agent_name": "Remediation & Verification Agent",
        "identity": "policy-gated remediation worker and independent observer",
        "responsibility": "execute account unlock, re-read state, and probe access",
        "inputs": ["DiagnosisResult", "StructuredIncident"],
        "outputs": ["ExecutionRecord", "VerificationResult"],
        "skills": ["AccountRemediationSkill", "AccessVerificationSkill"],
        "tools": ["IAMTool", "ApplicationTool"],
        "permissions": ["unlock_account", "read_status"],
        "context_memory": "approved plan and execution attempt",
        "risk_boundary": "automatic execution up to medium risk; high/critical require approval",
        "upstream": ["Manager Agent"],
        "downstream": ["Manager Agent"],
        "failure_strategy": "report observed failure even when the tool claims success",
    },
]
